export const UPDATE_FILM = 'UPDATE_FILM'
export const CLEAR_FILM = 'CLEAR_FILM'
export const UPDATE_FILMS = 'UPDATE_FILMS'

export const UPDATE_PERSON = 'UPDATE_PERSON'
export const CLEAR_PERSON = 'CLEAR_PERSON'
export const UPDATE_PEOPLE = 'UPDATE_PEOPLE'

export const UPDATE_LOCATION = 'UPDATE_LOCATION'
export const CLEAR_LOCATION = 'CLEAR_LOCATION'
export const UPDATE_LOCATIONS = 'UPDATE_LOCATIONS'

export const UPDATE_SPECIES = 'UPDATE_SPECIES'
export const CLEAR_SPECIES = 'CLEAR_SPECIES'
export const UPDATE_SPECIES_LIST = 'UPDATE_SPECIES_LIST'
