export const UPDATE_FILM = 'UPDATE_FILM'
export const CLEAR_FILM = 'CLEAR_FILM'
export const UPDATE_FILMS = 'UPDATE_FILMS'

export const UPDATE_PERSON = 'UPDATE_PERSON'
export const CLEAR_PERSON = 'CLEAR_PERSON'
export const UPDATE_PEOPLE = 'UPDATE_PEOPLE'
